### ISSUE TITLE
link to some examples of real world apps that use webview2

### ISSUE THREAD

**Issue by Poopooracoocoo** [MicrosoftEdge/WebView2Samples#100]
i want to see what webview2 is like without building it in vs

**Comment by HoldenPCaulfield** [comment]
I would like to see this as well.  Quite frankly, I am quite puzzled by the large amount of technical churn shown in this forum by hundreds of software developers, all apparently struggling with making this approach work.  Who is paying all these people to spend time working on a product that does not seem to work that well.   
Now...before you **flame me** take note that I am  not an expert C++ developer and my knowledge of the Win32 API is approximately "zero".  However, I like the idea of wrapping Edge/Chrome/whatever in a simple app that you can automate.  
Post a couple of apps written in vb.net or c#.net that use WV2 and post the source please.   Thanks in advance.

**Comment by Poopooracoocoo** [comment]
And it's *almost* funny how Microsoft has so many software development toolkits and can't just stick to one. I say almost because users are at expense. Microsoft Teams will switch to WebView2 from Electron. Both are from Microsoft though... React Native Windows was an option for MS Teams as well as it's built with React. It's scary for app developers who don't know what MS will actually support because MS itself doesn't. And yeah, WV2 being difficult doesn't help either.

**Comment by duke7553** [comment]
> And it's _almost_ funny how Microsoft has so many software development toolkits and can't just stick to one

This is wrong. It's incorrect to refer to these as "software development toolkits". They really could be application frameworks or entire app models which many customers have built their apps and potentially businesses on over the years. 

If you want to get specific, here's a breakdown of common technology from this industry:
* **UWP:** Dated marketing term for unmanaged/managed Windows apps that leverage CoreApplication
* **Win32:** The API native to Windows providing powerful functionality and a common control library
* **WinRT:** An app model based on enhanced COM principles which aims to reduce the complexity of calling Win32 APIs while delivering new features like a sandbox and capability system. <--- Technically Win32/COM under the hood
* **WPF:** .NET UI framework for building desktop apps with a rich UI
* **WinForms:** Wrapper over the classic Win32 API to easily build simple app UIs and abstract functionality for use in .NET
* **Electron:** Software framework used to build cross-platform desktop apps with web tech
* **React:** Set of libraries used by JS devs to create UI components for web apps
* **React Native:** Software framework that allows you to essentially write native apps in JS that can draw various native controls
* **WinUI Desktop:** Windows UI framework that's undocked from the OS's normal release cadence to facilitate use from non-UWP projects


> I say almost because users are at expense.

How so? I think it's incorrect to think every app (let alone every team at Microsoft) should use the same technology or else users dislike it.

> Microsoft Teams will switch to WebView2 from Electron. Both are from Microsoft though...

Not entirely correct. WebView2 is a control from Microsoft that leverages Chromium, but Electron is an entire software framework that isn't just Microsoft's. Microsoft does participate in the discussions produced by the consortium governing that project.

> React Native Windows was an option for MS Teams as well as it's built with React.

React != React Native Windows. Especially when considering the design goal of a modern M365 service like Teams is to be OS agnostic.

> It's scary for app developers who don't know what MS will actually support because MS itself doesn't.

If you follow Microsoft's commitments to the diverse array of tech they've supported, there's a great degree of transparency about what's supported. Virtually all of them are. Which is quite impressive. Some may receive more investment than others where it makes sense. Have you developed any software with one of these stacks yet? The only one really *at risk* of being replaced (by WinUI Desktop) is UWP, and even that's debatable for some reason. Nothing to fret about considering most consumer apps were never UWP. The rigidity of UWP really doesn't make sense either with Microsoft's latest position.


> And yeah, WV2 being difficult doesn't help either.

These sound like the words of someone who is simply assuming there's some kind of inherent complexity to WebView2 when they've never tried it.

@Poopooracoocoo Are you here to spend time complaining, or contribute actionable feedback based on your experiences building Windows apps? Because this feedback item is not only very incomplete (alongside your posts in other Microsoft GitHub repos) but rather off-topic compared to most of the items community members have opened in the repositories you interact with.

With all due respect, I strongly urge you (strictly from my own experience) to read the [contribution guidelines](https://github.com/microsoft/microsoft-ui-xaml/blob/main/CONTRIBUTING_feedback_and_requests.md).

**Comment by Poopooracoocoo** [comment]
yeah ok
