### ISSUE TITLE
Why does GetSDKBuildVersion remove the first two parts?

### ISSUE THREAD

**Issue by pushkin-** [MicrosoftEdge/WebView2Samples#233]
Why does [`GetSdkBuildVersion`](https://github.com/MicrosoftEdge/WebView2Samples/blob/c7c43e5d3cc8b4b53cd4d8f72f74ecd889960250/SampleApps/WebView2WindowsFormsBrowser/BrowserForm.cs#L1424C20-L1424C38) remove the first two parts of the version.

I get back "2210.55" though my Nuget version is "1.0.2210.55"

Should we not care about the first two parts?

**Comment by champnic** [comment]
In general the last two parts of the version string are the interesting ones, especially for knowing what runtime APIs are going to be available and compatible with installed runtimes. The "1.0" hasn't changed since we released WV2 SDK to GA, and we don't currently have plans for a 2.0 version. It's a possibility at some point in the future though.
